"""Offline demo data (``DATA_SOURCE_MODE=fixtures``).

The ``edgar/`` directory holds the hand-built SEC-format fixtures (companyfacts / submissions /
company_tickers, plus one segment XBRL instance) generated by ``tests/fixtures/edgar/build_fixtures.py``.
They are the canonical copy: the unit tests load them from here, and the worker serves them in demo
mode through :class:`app.data.demo.edgar_client.FixtureEdgarClient`, so the app can run end to end
with no network access to SEC / Yahoo / FRED.

Demo market data is deterministic: a fixed price and share count per ticker and a fixed risk-free rate.
Every run built in this mode carries :data:`DEMO_DATA_FLAG` in its data-confidence flags.

Never enable this mode in a deployed environment.
"""

from __future__ import annotations

import json
from functools import cache
from pathlib import Path
from typing import Any

DEMO_EDGAR_DIR = Path(__file__).parent / "edgar"

DEMO_DATA_FLAG = "DEMO DATA — not live filings/prices"
DEMO_RISK_FREE_RATE = 0.042
DEMO_AS_OF = "2025-08-29T20:00:00+00:00"


# ticker -> (price USD, shares outstanding). Rough late-summer-2025 levels; deterministic by design.
DEMO_PRICES: dict[str, tuple[float, float]] = {
    "AAPL": (232.0, 14_840e6),
    "MSFT": (506.0, 7_433e6),
    "GOOGL": (212.0, 12_100e6),
    "WMT": (96.0, 7_975e6),
    "NUE": (140.0, 230e6),
    "SNOW": (225.0, 337e6),
    "JPM": (300.0, 2_750e6),
    "TRV": (275.0, 225e6),
    "MET": (80.0, 665e6),
    "O": (58.0, 915e6),
    "EOG": (125.0, 545e6),
    "HON": (220.0, 635e6),
    "PFE": (25.0, 5_686e6),
    "VKTX": (28.0, 112e6),
    "ALAB": (180.0, 165e6),
    "CVII": (10.6, 138e6),
    "EPD": (31.0, 2_165e6),
    "NEM": (72.0, 1_100e6),
    "DUK": (122.0, 777e6),
    "TSM": (230.0, 5_187e6),
}


@cache
def _read(name: str) -> str:
    return (DEMO_EDGAR_DIR / name).read_text()


def has_file(name: str) -> bool:
    return (DEMO_EDGAR_DIR / name).is_file()


def load_companyfacts(ticker: str) -> dict[str, Any]:
    """Fresh (mutable) copy of ``{TICKER}_companyfacts.json``."""
    return json.loads(_read(f"{ticker.upper()}_companyfacts.json"))


def load_submissions(ticker: str) -> dict[str, Any]:
    return json.loads(_read(f"{ticker.upper()}_submissions.json"))


def load_company_tickers() -> dict[str, Any]:
    return json.loads(_read("company_tickers.json"))


def segments_document(ticker: str) -> bytes | None:
    """The latest 10-K's XBRL instance with segment facts, when the fixture set has one."""
    path = DEMO_EDGAR_DIR / f"{ticker.upper()}_segments_instance.xml"
    return path.read_bytes() if path.is_file() else None


def fixture_tickers() -> tuple[str, ...]:
    """Tickers with a submissions fixture (the ones demo mode can serve), sorted."""
    return tuple(
        sorted(p.name.removesuffix("_submissions.json") for p in DEMO_EDGAR_DIR.glob("*_submissions.json"))
    )
